from typing import Any, Generator

import pytest
import json
import time

from api.clients.abra_client import AbraClient
from api.clients.postgres_client import PostgresClient
from api.models.abra_model import LoginRequestModel, ProductUploadRequestModel
from config import settings
from pathlib import Path
from datetime import datetime


@pytest.fixture
def abra_client() -> AbraClient:
    return AbraClient()

@pytest.fixture
def logged_in_seller() -> Generator[AbraClient, Any, None]:
    abra_client = AbraClient()
    login_request_data = LoginRequestModel(
        email = settings.seller.email,
        password = settings.seller.password
    )
    abra_client.login(login_request_data=login_request_data)
    yield  abra_client

    #abra_client.sign_out()

@pytest.fixture
def logged_in_supplier() -> Generator[AbraClient, Any, None]:
    abra_client = AbraClient()
    login_request_data = LoginRequestModel(
        email = settings.supplier.email,
        password = settings.supplier.password
    )
    abra_client.login(login_request_data=login_request_data)
    yield  abra_client

    #abra_client.sign_out()

@pytest.fixture(autouse=True)
def postgres_client() -> PostgresClient:
    return PostgresClient()


@pytest.fixture
def autogenerate_product(logged_in_supplier):
    json_path = Path(__file__).parent.parent / "test_data" / "product_payload.json"
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    current_time = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    data["name"] = f"test_autogenerated_{current_time}"
    payload = ProductUploadRequestModel(**data)
    response = logged_in_supplier.create_product(product_data=payload)
    assert response.ok is True, f"Setup failed: Product '{data["name"]}' creation failed. Response: {response.text}"

    products = logged_in_supplier.get_products_list(params={"query": data["name"]})
    product_id = products[0]['result']['products']['id']

    if product_id is None:
       pytest.fail(f"Setup failed: Product '{data["name"]}' was created but not found in list.")
    yield product_id

    print(f"\n[Cleanup] Deleting product ID: {product_id}")
    logged_in_supplier.delete_products(product_ids=[product_id])






