[pytest]

markers =
    smoke: isolated endpoint tests
    e2e: end-to-end tests
    api: api method tests

# Ignore SSL certificate warnings for test environment
filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning

